### ISSUE TITLE
Better windows support

### ISSUE THREAD

**Issue by wight554** [jnoortheen/vscode-xonsh#33]
Hello there
Noticed windows doesn't runs well with this ext until you do
`"pyls.executable": "pyls.exe"`
Unfortunately this isn't great for cross-os settings sync, so would be better to workaround it at extension level

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
1. was there any error in particular?
2. are you able to use python extension with pyls server selected?

**Comment by wight554** [comment]
No specific error, just says pyls not installed

**Comment by wight554** [comment]
Upd. works file in python extension

**Comment by jnoortheen** [comment]
unfortunately windows is not my main drive. a PR is welcome

**Comment by wight554** [comment]
I'm not really into extensions dev, so idk how to test
But quick fix can be smth like
```
  if (executable) {
    return which(executable);
  }
```
to
```
  if (executable) {
    const isWindows = process.platform ==='win32';
    return which(isWindows && !executable.includes('.exe') ? `${executable}.exe` : executable);
  }
```

**Comment by jnoortheen** [comment]
please check out here https://github.com/jnoortheen/vscode-xonsh#development 

once you open this extension project in vs code, you can launch an instance with extension installed using f5

**Comment by wight554** [comment]
checked, works
https://github.com/jnoortheen/vscode-xonsh/pull/34
