### ISSUE TITLE
Add xontrib topic to the repository

### ISSUE THREAD

**Issue by anki-code** [jnoortheen/vscode-xonsh#41]
Hi!

I think it will be great to add the `xontrib` tag to repository topics. I understand that xontrib topic is mostly using for the installable extensions for xonsh. But xontrib means "contribution" and it's not a problem to add this repository to the list of [xontribs on Github](https://github.com/topics/xontrib) to get more stars and attention.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
As you have mentioned, xontrib means xonsh plugins. It is already mentioned in the Xonsh's editor support page.
