### ISSUE TITLE
Rename to vscode-xonsh and repo settings

### ISSUE THREAD

**Issue by anki-code** [jnoortheen/vscode-xonsh#5]
Hi! Thank you for this great start!

Could you please:

1. Rename the repo to `vscode-xonsh` like [vscode-python](https://github.com/Microsoft/vscode-python)

2. Add topics: `xonsh`, `vscode` to the repo

3. Add "Social preview" image in repo Settings-Options:

![image](https://user-images.githubusercontent.com/1708680/95301849-d4e12a00-0889-11eb-94ba-d4c024283cc2.png)

Thanks!

**Comment by jnoortheen** [comment]
done

**Comment by anki-code** [comment]
You can promote the extension in [the xonsh Gitter channel](https://gitter.im/xonsh/xonsh).

**Comment by jnoortheen** [comment]
Ok will do.

**Comment by anki-code** [comment]
Also I've found the [IDE thread](https://groups.google.com/g/xonsh/c/Ugy4zk_8--0) in [xonsh Google group](https://groups.google.com/g/xonsh).

And I've create the [PR to add your extension to the docs](https://github.com/xonsh/xonsh/pull/3849).
