### ISSUE TITLE
Add suggestion support in python operator

### ISSUE THREAD

**Issue by anki-code** [jnoortheen/vscode-xonsh#6]
Hi! Thank you for the extension!

I think it will be great to create distinct issues for everything we want instead of listing in the README.

Add suggestion support in python operator:

![Screenshot_20201007_124530](https://user-images.githubusercontent.com/1708680/95315341-07dfe980-089b-11eb-8fae-f853c54b7b7c.png)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
yes it was just a placeholder. My aim was to finish it in less time. we will move it here afterwards.
